### ISSUE TITLE
Buttons 

### ISSUE THREAD

**Issue by ahmedlhanafy** [react-native-paper/react-native-paper#3]
[Material Design Docs Link](https://material.google.com/components/buttons.html#)

**TODO:**
- [x] Ability to customize text color
- [x] Disabled button
- [x] Button with icon
- [x] Button with loading indicator
